### ISSUE TITLE
speed show to hight

### ISSUE THREAD

**Issue by hnkeyang** [zpeters/speedtest#86]
my bandwidth limit is 10Mbps, i use this tools show this: 
Ping (Lowest): 7.90 ms | Download (Max): 18.68 Mbps | Upload (Max): 17.45 Mbps,
i use iftop monitor bandwidth max is 10Mbps

**Comment by zpeters** [comment]
Thank you for reporting.  I will do some testing on my side and see what i find

**Comment by zpeters** [comment]
Would you kindly test this same process with the "nload" program and see if you get similar results.  The measurements will never be exactly the same as a tool like iftop or nload because it is measuring different things.  

With speedtest you are measuring "goodput" (https://en.wikipedia.org/wiki/Goodput) which is the application level speed.  Meaning that we aren't concerned with tcp overhead, congestion, etc just the time it takes to transfer the data that you care about.  Tools like iftop or nload measure at the network level so they will take into account protocol overhead, etc.

What we should be seeing is that the download and upload speeds shown by speedtest will be slightly higher then the more accurate tools like nload or iftop.

**Comment by hnkeyang** [comment]
i tested and use nload and iftop monitor traffic, test result is :Ping (Lowest): 9.56 ms | Download (Max): 17.02 Mbps | Upload (Max): 14.73 Mbps, nload and iftop show's download speed  are the same 10Mbps

**Comment by zpeters** [comment]
Interesting...Thank you for looking at this.  I will do some testing with a simulated bandwidth cap and see if i can figure something out.

**Comment by zpeters** [comment]
See #85
